### ISSUE TITLE
Angular1 UI router incompatibility with Portal Routing

### ISSUE THREAD

**Issue by egucciar** [me-12/single-spa-portal-example#1]
Hello,

First off, thanks so much for this example. This speeds up the development of the portal architecture significantly. So far you have solved a lot of the problems we would have faced had we started from scratch with.

However we have one issue, we are using angular-1 single spa portal library with UI router. Once the angular1 app is loaded, all other routes / apps cease to load. Guessing this is due to an incompatibility between portal routing and angular1 routing

any ideas?

**Comment by me-12** [comment]
I have added an example with Angular 1.6 in the latest commit https://github.com/me-12/single-spa-portal-example/commit/46e9476593ab7fa91f34d5b4cdc664c92e6dc576 .

Take a look at these lines in routes.js: 
```
        // make sure angular does not rewrite our urls, since they are set by the portal
        $locationProvider.hashPrefix('');
        $locationProvider.html5Mode({
            enabled: false,
            requireBase: false,
        });
```
This fixed the routing issues for me. Hopefully it will help you as well.

**Comment by me-12** [comment]
I assume this issue has been clarified. Closing for now.
