### ISSUE TITLE
Cannot find module '../assets/angular-logo.png'.

### ISSUE THREAD

**Issue by abelkbil** [me-12/single-spa-portal-example#19]
Hi Michael,

Awesome repo, especially stand alone and separate build and deploy.  I got an error on  below.  But app works fine.
`import angularImg = require("../assets/angular-logo.png");`

./src/app2.component.ts
(5,29): error TS2307: Cannot find module '../assets/angular-logo.png'.

This is not an issue

![image](https://user-images.githubusercontent.com/1478274/38302106-2894d3c4-381f-11e8-8027-0303b0b99ecf.png)

**Comment by me-12** [comment]
I have pushed a (hopefully) fix. Could you check if it works?

**Comment by me-12** [comment]
Closing, since this should be fixed for a while now.
