### ISSUE TITLE
Inter app communication layer - distrobute auth info?

### ISSUE THREAD

**Issue by nigel-dewar** [me-12/single-spa-portal-example#24]
Hi there.

Im wondering with the store app layer, could this be used to store some authz info?

Say i have 2 child apps, 1 that is open and 1 that is restricted to users with a certain role, Can i feed authz into the store and have this consumed by all the child apps as they bootstrap/mount?

I cant see any reason why not. Im just trying to get an understanding how global config and shared info like this can feed into the solution as a whole.

I think this sample shows how, but im asking to get your expert point of view on how cross cutting concerns like authz etc would be handled?

**Comment by me-12** [comment]
Hello nigel-dewar,

of course you can use the globalEventDistributor to distribute arbitrary data to each child app. Just keep in mind, that this will distribute the auth data to ALL child apps. If you have multiple apps developed by different teams, they will also be able to read that token.

Another way to store your Tokens would be to use the localStorage/sessionStorage or Cookies with the setting `Secure `and `HttpOnly`. Both solutions have their advantages and disadvantages. For a quick introduction about this topic, have a look at: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by nigel-dewar** [comment]
Cool thanks so much for your reply and good advice. Ill check this out.

Cheers

On 19 May 2018 9:04 PM, Michael <notifications@github.com> wrote:

Hello nigel-dewar,

of course you can use the globalEventDistributor to distribute arbitrary data to each child app. Just keep in mind, that this will distribute the auth data to ALL child apps. If you have multiple apps developed by different teams, they will also be able to read that token.

Another way to store your Tokens would be to use the localStorage/sessionStorage or Cookies with the setting Secureand HttpOnly. Both solutions have their advantages and disadvantages. For a quick introduction about this topic, have a look at: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by amit131** [comment]
It would be awesome if there is an example showing auth layer along side existing stuff as it would be really helpful when it comes to follow best practices.
