### ISSUE TITLE
Illustrate how to handle images in child apps

### ISSUE THREAD

**Issue by michael-robison** [me-12/single-spa-portal-example#3]
First off, I just want to say thank you. This repo is the only example I've found for module loading child applications using single-spa.

Something I would love to see is how to have the child applications load images. So far, I have noticed child applications try to load images, but they are requested from the parent server.

If you have any ideas of how to do this, I would love to see it added to your example.

**Comment by me-12** [comment]
Have a look at this PR: https://github.com/me-12/single-spa-portal-example/pull/6

In this solution I have added a proxy server to the portal server that is responsible to resolve all paths correctly: https://github.com/me-12/single-spa-portal-example/pull/6/files#diff-039a2e2e7c92fd4d3ff9309ebaea6080R54

So basically all request to "/app1/something" being redirected to "http://localhost:9001/something"

What I like about this solution is, that there is now only one place where you configure the app URLs and that is not in your source code. The app -> URL mapping can happen solely on the proxy/server side. So you don't need to deploy the portal app all the time if only the URL of a child app changes.

So these places are obsolete: https://github.com/me-12/single-spa-portal-example/pull/6/files#diff-d864c6185775801cd5c4d5cacb3e1f4eL15

What I don't like is, that your child apps have to prefix their src attribute. Luckily that can be done in the webpack config. So it is not absolutely bad. https://github.com/me-12/single-spa-portal-example/pull/6/files#diff-ccddefeb4c7d25c0de2f9ec6ed81a9bfR32

In a production environment you will need to have a proxy server somewhere or at least be able to configure your web server with URL rewrites.

**Comment by me-12** [comment]
I assume this issue has been clarified. Closing for now.
