### ISSUE TITLE
Run application on Apache webserver

### ISSUE THREAD

**Issue by rberkovi** [me-12/single-spa-portal-example#33]
All standalone builds tied to webpack. 
How to prepare builds for apache webserver. Their is no .angular-cli.json.

**Comment by me-12** [comment]
Why would you need a .angular-cli.json. Just go into any app folder you want and buld the app. I.e. if you want to build the app "app2Angular" you do:

1. `cd app2Angular`
2. `npm run build:portal`

The output files are in the `release `folder. Now grab them and upload them to any webserver you want.

**Comment by rberkovi** [comment]
Thank you,
Will this mode support globaleventdispatcher?

**Comment by me-12** [comment]
Sure.
