### ISSUE TITLE
Unable to `npm install` Angular apps (app2, app5)

### ISSUE THREAD

**Issue by bjolletz** [me-12/single-spa-portal-example#41]
For the Angular apps (app2 and app5), npm install fails with "404 Not Found: eslint-scope@3.7.2". It seems like eslint-scope 3.7.2 was compromised and that it has been removed from npm repositories, which is probably the cause.

**Comment by me-12** [comment]
Thanks for the heads-up. I have updated the packages. If you like, you can test it again.

**Comment by bjolletz** [comment]
Thanks for the quick fix, seems to work fine now!
