### ISSUE TITLE
Unable to provide styleUrl for the Angular component 

### ISSUE THREAD

**Issue by jameelvm** [me-12/single-spa-portal-example#44]
I have downloaded this github application and able to run successfully by loading all single spa applications. But I am facing one problem when  specify the style url in Angular component.
```

@Component({
    selector: 'app5',
    styleUrls:["./app5.component.scss"],_
	template: `
		<div style="margin-top: 100px;">
            <img [src]="angularImg" style="width: 100px;"/> <br />
			This was rendered by App5 which is written in Angular 6
		</div>
        <br />
```

I have installed all the dependencies required for style loader ,scss loader , post css loader but finally I am getting the below error . 
```
ERROR in ./src/app5.component.scss
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: C:\MyCave\jStudio\LinqIndepth\CSharp.Linq\MicrofrontEndResearch\SingleSpaPortal\Application\app5Angular\src
    at config.load.then (C:\MyCave\jStudio\LinqIndepth\CSharp.Linq\MicrofrontEndResearch\SingleSpaPortal\Application\app5Angular\node_modules\postcss-load-config\src\index.js:55:15)
 @ ./src/app5.component.ts 46:21-53
 @ ./src/main-module.ts
 @ ./src/singleSpaEntry.ts
 @ multi (webpack)-dev-server/client?http://localhost:9005 src/singleSpaEntry.ts
i ｢wdm｣: Failed to compile.
```
for resolving this error I have installed postconfig package also , but still I am getting the same error
is there any workaround for this??

**Comment by fireappsAdmin** [comment]
Hi there, 
Do you have a postcss.config in your directory? This is what mine looks like in my src folder. 
`module.exports = {
	map: false,
	from: './src/assets/styles',
	to: './dist',
}`

It describes [here ](https://github.com/postcss/postcss-loader)how to make the config file if you want too.

Hope that helps!

**Comment by jameelvm** [comment]
Is there any sample config file which work for this git hub application?

**Comment by fireappsAdmin** [comment]
The lightest weight postcss config is the one I listed above. 
`module.exports = { map: false, from: './your/directory/path', to: './yourOutputFolder', }`
Just create a postcss.config.js file in your src directory and copy and paste the code in.
This is also the example they give on their website. 
I have postcss up and running with that config on single-spa-portal-example.

**Comment by maciej-w** [comment]
In your `webpack.config.js` find `                {
                    test: /\.(css|scss)$/,
                    loaders: ['to-string-loader', 'css-loader', 'sass-loader']
                },`
and remove `scss`. 
Looks like there is another scss loader below and they moght not work correctly together all the time.
