### ISSUE TITLE
Uncaught Error: Application 'appname' died in status LOADING_SOURCE_CODE: Unexpected token <

### ISSUE THREAD

**Issue by sri1980** [me-12/single-spa-portal-example#49]
I have angular 4 app and created singleSpaEntry.js file to bootstrap the app with all lifecyle functions implemented. Exposed below url to load singleSpaEntry.js which will be called from portal app.

https://url/singleSpaEntry.js

It works fine and able to load the app when i access this url . Getting error when i call this url from portal.js

Thanks for your help in advance.

**Comment by me-12** [comment]
Doublicate of https://github.com/me-12/single-spa-portal-example/issues/50? Closing for now.
