### ISSUE TITLE
Add link to this repo from single-spa documentation

### ISSUE THREAD

**Issue by joeldenning** [me-12/single-spa-portal-example#9]
@me-12 are you okay with me adding a link to this repo in the single-spa documentation? I've already created https://github.com/CanopyTax/single-spa/pull/187/files, which does so, but wanted to ask you about it first.

Also, thank you for your work on single-spa, single-spa-portal-example, and for jumping into the issue queus and helping out there. Would you be interested in hearing about and helping out with some of the exciting new things we've got planned for with single-spa? And maybe joining in on some of the discussions we're having about the future direction of single-spa.

If so, we're using slack to coordinate some of that, along with [github's projects for single-spa](https://github.com/CanopyTax/single-spa/projects). You can join the slack with [this link](https://join.slack.com/t/single-spa/shared_invite/enQtMzIwMTcxNTU3ODQyLTM1Y2U1OWMzNTNjOWYyZDBlMDJhN2VkYzk3MDI2NzQ2Nzg0MzMzNjVhNWE2YjVhMTcxNjFkOWYzMjllMmUxMjk), and once you're in I will invite you to a group chat where we discuss these types of things.

**Comment by me-12** [comment]
Hi @joeldenning, as stated in the issue earlier, I am happy with my repo being linked in the examples readme. 

I have just joined slack. I have chosen the same name (me-12) for slack. Looking forward to chatting with you guys there.

**Comment by joeldenning** [comment]
Awesome, thanks
